# Generated by Django 5.2.6 on 2025-09-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='category',
            field=models.CharField(choices=[('camera', 'Camera'), ('lens', 'Lens'), ('action_camera', 'Action Camera'), ('gopro', 'GoPro'), ('tripod', 'Tripod'), ('gimbal', 'Gimbal'), ('battery', 'Battery'), ('memory_card', 'Memory Card'), ('bag', 'Camera Bag'), ('other', 'Other')], max_length=20),
        ),
    ]
