# Generated by Django 5.2.6 on 2025-09-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_gear_brand_gear_price_alter_gear_category_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rental',
            name='deposit_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gear',
            name='category',
            field=models.CharField(choices=[('camera', 'Camera'), ('lens', 'Lens'), ('action_camera', 'Action Camera'), ('gimbal', 'Gimble'), ('battery', 'Battery'), ('memory_card', 'Memory Card'), ('other', 'Other')], max_length=20),
        ),
    ]
